[build]
  base = "web"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle SPA routing - redirect everything except functions and assets to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
